name: Package and release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses:
          actions/checkout@v2
        with:
          fetch-depth: 20
      - name: Package and release
        uses: BigWigsMods/packager@master
        with:
          args: -g 1.13.6 -n "{package-name}-{project-version}"
